// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListRunningEC2Instances() {
  return window['go']['main']['App']['ListRunningEC2Instances']();
}
